import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  gestureRoot: { flex: 1 },
  safe: { flex: 1, backgroundColor: "#fffaf7" },
  page: { flex: 1 },
  keyboardAvoiding: { flex: 1 },
  stylingScroll: { flexGrow: 1, paddingBottom: 28 },
  scroll: { padding: 20, paddingBottom: 30 },
  topline: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
  },
  eyebrow: {
    color: "#aa796d",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1.4,
  },
  title: {
    fontSize: 29,
    fontWeight: "600",
    color: "#403735",
    letterSpacing: 0.15,
    marginTop: 2,
  },
  roundAdd: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: "#b8604e",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#7a2e20",
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 3,
  },
  section: { marginBottom: 26 },
  sectionHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  sectionTitle: { fontSize: 18, color: "#302a29", fontWeight: "600" },
  tip: { fontSize: 12, color: "#967f78", marginTop: 3 },
  more: { fontSize: 13, color: "#b8604e", fontWeight: "700" },
  row: { flexDirection: "row", gap: 10 },
  homeImageScroller: { gap: 10, paddingRight: 20 },
  homePreviewCard: { flexShrink: 0 },
  collectionSelectionGrid: { flexWrap: "wrap" },
  itemCard: { width: "31.9%" },
  itemImage: {
    width: "100%",
    aspectRatio: 1,
    borderRadius: 15,
    backgroundColor: "#f1e5df",
  },
  itemLabel: { color: "#695e5a", fontSize: 12, marginTop: 6 },
  empty: {
    alignItems: "center",
    alignSelf: "stretch",
    paddingTop: 86,
    paddingHorizontal: 20,
  },
  emptyIcon: {
    width: 78,
    height: 78,
    borderRadius: 39,
    backgroundColor: "#f7e9e4",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 15,
  },
  emptyTitle: { fontSize: 18, fontWeight: "800", color: "#332d2c" },
  emptyBody: {
    fontSize: 14,
    color: "#8e817c",
    marginTop: 7,
    textAlign: "center",
  },
  emptyAction: {
    flexDirection: "row",
    gap: 5,
    alignItems: "center",
    backgroundColor: "#b8604e",
    paddingHorizontal: 16,
    paddingVertical: 11,
    borderRadius: 22,
    marginTop: 19,
  },
  emptyActionText: { color: "#fff", fontWeight: "700" },
  tabbar: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#eee3df",
    paddingTop: 12,
    shadowColor: "#5f4139",
    shadowOpacity: 0.05,
    shadowRadius: 9,
    shadowOffset: { width: 0, height: -3 },
    elevation: 5,
  },
  tab: { flex: 1, alignItems: "center", gap: 3 },
  tabText: { fontSize: 11, color: "#9b918e" },
  activeTabText: { color: "#b8604e", fontWeight: "700" },
  helper: { color: "#8e817c", fontSize: 13, marginTop: -14, marginBottom: 9 },
  mannequinWrap: {
    height: 500,
    alignItems: "center",
    position: "relative",
    paddingTop: 8,
  },
  manHead: {
    height: 76,
    width: 79,
    borderRadius: 40,
    backgroundColor: "#f0ece9",
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  manNeck: {
    height: 41,
    width: 62,
    borderRadius: 11,
    backgroundColor: "#e9e2de",
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    marginTop: -4,
    zIndex: 1,
  },
  manTorso: {
    width: 201,
    height: 165,
    backgroundColor: "#f2eeeb",
    borderRadius: 51,
    marginTop: -1,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  manDress: {
    height: 260,
    borderBottomLeftRadius: 80,
    borderBottomRightRadius: 80,
  },
  manLegs: {
    width: 143,
    height: 128,
    backgroundColor: "#eee8e4",
    marginTop: 2,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    borderBottomLeftRadius: 29,
    borderBottomRightRadius: 29,
  },
  manFeet: {
    width: 180,
    height: 59,
    borderRadius: 21,
    backgroundColor: "#e9e2de",
    marginTop: 5,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  manFeetDress: { marginTop: 6 },
  partImage: { width: "100%", height: "100%", resizeMode: "cover" },
  partHint: { alignItems: "center" },
  partText: { fontSize: 10, color: "#936f66", marginTop: 1 },
  rule: { height: 1, backgroundColor: "#eee3df", marginBottom: 18 },
  chips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
    marginBottom: 8,
  },
  chip: {
    paddingHorizontal: 13,
    paddingVertical: 8,
    borderRadius: 19,
    backgroundColor: "#f3ece8",
    borderWidth: 1,
    borderColor: "transparent",
  },
  chipActive: { backgroundColor: "#f9ded5", borderColor: "#c87563" },
  chipText: { color: "#756863", fontSize: 13 },
  chipTextActive: { color: "#9e4534", fontWeight: "700" },
  input: {
    borderWidth: 1,
    borderColor: "#e5d9d4",
    backgroundColor: "#fff",
    borderRadius: 13,
    paddingHorizontal: 14,
    height: 47,
    marginTop: 8,
    fontSize: 14,
    color: "#322b29",
  },
  primaryButton: {
    flexDirection: "row",
    height: 51,
    borderRadius: 15,
    backgroundColor: "#b8604e",
    marginTop: 20,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  disabled: { opacity: 0.42 },
  primaryText: { color: "#fff", fontWeight: "800", fontSize: 15 },
  cancelText: { color: "#b8604e", fontWeight: "700" },
  headerActions: { flexDirection: "row", alignItems: "center", gap: 14 },
  collectionHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 9,
  },
  headerSave: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#b8604e",
    alignItems: "center",
    justifyContent: "center",
  },
  outfitCard: { width: "31.9%", position: "relative" },
  detailHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 15,
  },
  detailHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    width: 86,
  },
  detailHeaderActionsRight: { justifyContent: "flex-end" },
  detailHeaderTitle: { flex: 1, alignItems: "center" },
  detailTitle: {
    fontSize: 23,
    color: "#292423",
    fontWeight: "800",
    marginTop: 2,
  },
  selectionHeaderButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#f7eae5",
    alignItems: "center",
    justifyContent: "center",
  },
  hiddenHeaderButton: { opacity: 0 },
  deleteHeaderButton: { backgroundColor: "#fce8e5" },
  selectionBar: {
    marginBottom: 10,
    marginHorizontal: 20,
    padding: 11,
    borderRadius: 11,
    backgroundColor: "#f7eae5",
    flexDirection: "row",
    justifyContent: "space-between",
    color: "#5b4f4b",
  },
  collectionSelectionBar: {
    marginBottom: 10,
    padding: 11,
    borderRadius: 11,
    backgroundColor: "#f7eae5",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  selectionActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 18,
  },
  selectAllText: { color: "#9e5848", fontWeight: "700" },
  deleteText: { color: "#b13e31", fontWeight: "800" },
  grid: { paddingHorizontal: 15, paddingBottom: 90 },
  selectionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: -5,
  },
  gridCard: { width: "33.333%", padding: 5, position: "relative" },
  sortableGridCard: { width: "100%", aspectRatio: 1, position: "relative" },
  gridImage: {
    width: "100%",
    aspectRatio: 1,
    borderRadius: 13,
    backgroundColor: "#eee4df",
  },
  detailAddTile: {
    width: "100%",
    aspectRatio: 1,
    borderRadius: 13,
    borderColor: "#d9c7c0",
    borderWidth: 1,
    borderStyle: "dashed",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fffaf7",
  },
  selectedCard: { opacity: 0.64 },
  check: {
    position: "absolute",
    right: 10,
    top: 10,
    backgroundColor: "#b8604e",
    borderRadius: 12,
    height: 22,
  },
  collectionCheck: {
    position: "absolute",
    right: 6,
    top: 6,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#b8604e",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1,
  },
  floatingAdd: {
    position: "absolute",
    bottom: 22,
    alignSelf: "center",
    width: 55,
    height: 55,
    borderRadius: 28,
    backgroundColor: "#b8604e",
    alignItems: "center",
    justifyContent: "center",
    elevation: 4,
  },
  modalShade: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(45,35,31,.4)",
  },
  sheet: {
    backgroundColor: "#fffaf7",
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    padding: 20,
    paddingBottom: 28,
  },
  sheetGrip: {
    alignSelf: "center",
    width: 36,
    height: 4,
    backgroundColor: "#decfc9",
    borderRadius: 3,
    marginBottom: 14,
  },
  sheetTitleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sheetTitle: { fontSize: 20, fontWeight: "800", color: "#2f2927" },
  fieldLabel: {
    color: "#453c3a",
    fontWeight: "700",
    marginTop: 19,
    fontSize: 14,
  },
  required: { color: "#c84d3c" },
  uploadRow: { flexDirection: "row", flexWrap: "wrap", gap: 9, marginTop: 10 },
  previewWrap: { width: 67, height: 67 },
  preview: { width: "100%", height: "100%", borderRadius: 10 },
  removePreview: {
    position: "absolute",
    right: -5,
    top: -5,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: "#7b4a41",
    alignItems: "center",
    justifyContent: "center",
  },
  uploadTile: {
    width: 67,
    height: 67,
    borderRadius: 10,
    borderColor: "#d9c7c0",
    borderWidth: 1,
    borderStyle: "dashed",
    alignItems: "center",
    justifyContent: "center",
  },
  uploadText: { color: "#8a7068", fontSize: 11, marginTop: 2 },
  sourceRow: { flexDirection: "row", gap: 10, marginTop: 10 },
  sourceButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: "#f3ebe7",
    borderRadius: 9,
  },
  sourceText: { fontSize: 12, color: "#725b55", fontWeight: "600" },
  imageSourceOptions: { marginTop: 18, gap: 10 },
  imageSourceOption: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#eaded9",
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 13,
  },
  imageSourceIcon: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: "#f8ece7",
    alignItems: "center",
    justifyContent: "center",
  },
  imageSourceCopy: { flex: 1, marginLeft: 12 },
  imageSourceTitle: { color: "#453c3a", fontSize: 15, fontWeight: "600" },
  imageSourceSubtitle: { color: "#967f78", fontSize: 12, marginTop: 2 },
  modalActions: { flexDirection: "row", gap: 10, marginTop: 22 },
  secondaryButton: {
    flex: 1,
    height: 48,
    borderRadius: 13,
    backgroundColor: "#f0e8e4",
    justifyContent: "center",
    alignItems: "center",
  },
  confirmButton: {
    flex: 1.5,
    height: 48,
    borderRadius: 13,
    backgroundColor: "#b8604e",
    justifyContent: "center",
    alignItems: "center",
  },
  chooser: {
    minHeight: 390,
    maxHeight: "76%",
    backgroundColor: "#fffaf7",
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    padding: 20,
  },
  chooserGrid: { paddingTop: 14 },
  choice: { width: "33.333%", padding: 5 },
  choiceImage: {
    width: "100%",
    aspectRatio: 1,
    borderRadius: 11,
    backgroundColor: "#efe5e0",
  },
  choiceText: {
    fontSize: 11,
    color: "#6c615d",
    marginTop: 4,
    textAlign: "center",
  },
});
